addons: {}
after_success:
- ./df-build.sh
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
notifications: {}
script: mvn test-compile
sudo: 'false'
# Modified by IntegrationTestInstrumentation at 2016-07-01 07:56:24.928151
