language: java
before_install:
  - wget https://s3.amazonaws.com/external-ci-artifacts/agents/dfbuild-agent.jar
  - wget https://s3.amazonaws.com/external-ci-artifacts/agents/dfbuild-agent-ext.jar
env:
  global:
    - V_BUILD_TIME=$(($(date +%s%N)/1000000))
    - V_PROJECT_DIR=$(pwd)
    - V_CURRENT_PROJECT=$(basename $PWD)
    - V_PACKAGING_URL=s3://external-ci-artifacts/artifacts/
    - JAVA_TOOL_OPTIONS=-javaagent:dfbuild-agent.jar=PACKAGING_BASE_URI=$V_PACKAGING_URL,PRODUCT_KEY=dfb.$V_CURRENT_PROJECT/,BUILD_KEY=$V_BUILD_TIME/,MODULES_KEY=modules/,START_TIME=0,BUILD_BASE_DIR=$V_PROJECT_DIR
    - AWS_ACCESS_KEY_ID=AKIAIIU2LBOCCKXAIFZQ
    - AWS_SECRET_ACCESS_KEY=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

script: mvn clean integration-test


